/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/common/BaseButton.vue')['default']
    BaseChart: typeof import('./src/components/common/BaseChart.vue')['default']
    BaseCheckbox: typeof import('./src/components/common/BaseCheckbox.vue')['default']
    BaseForm: typeof import('./src/components/common/BaseForm.vue')['default']
    BaseInput: typeof import('./src/components/common/BaseInput.vue')['default']
    BaseNotification: typeof import('./src/components/common/BaseNotification.vue')['default']
    BasePaginate: typeof import('./src/components/common/BasePaginate.vue')['default']
    BaseSearch: typeof import('./src/components/common/BaseSearch.vue')['default']
    BaseSelectBox: typeof import('./src/components/common/BaseSelectBox.vue')['default']
    BaseTable: typeof import('./src/components/common/BaseTable.vue')['default']
    BaseTextArea: typeof import('./src/components/common/BaseTextArea.vue')['default']
    BaseTitle: typeof import('./src/components/common/BaseTitle.vue')['default']
    ConfirmDialog: typeof import('./src/components/common/ConfirmDialog.vue')['default']
    DealDetails: typeof import('./src/components/dashboard/DealDetails.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    Header: typeof import('./src/components/common/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Link: typeof import('./src/components/auth/Link.vue')['default']
    ListStaCard: typeof import('./src/components/dashboard/ListStaCard.vue')['default']
    MenuItem: typeof import('./src/components/common/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaleDetails: typeof import('./src/components/dashboard/SaleDetails.vue')['default']
    Sidebar: typeof import('./src/components/common/Sidebar.vue')['default']
    StaCard: typeof import('./src/components/dashboard/StaCard.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Title: typeof import('./src/components/auth/Title.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
